# Copyright (c) 2018-2022 The MobileCoin Foundation
{{- $hosts := split "\n" (include "fogServices.fogReportHosts" . | trim) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fogServices.fullname" . }}-fog-report-grpc
  labels:
    app: fog-report
    {{- include "fogServices.labels" . | nindent 4 }}
  annotations:
    {{- if eq (include "fogServices.blocklist.enabled" .) "true" }}
    haproxy.org/blacklist: {{ include "fogServices.blocklist.pattern" . }}
    {{- end }}
    {{- toYaml .Values.fogReport.ingress.common.annotations | nindent 4 }}
    {{- toYaml .Values.fogReport.ingress.grpc.annotations | nindent 4 }}
spec:
{{- if .Values.global.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range $hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ include "fogServices.fullname" . }}-fog-tls
{{- end }}
  rules:
  {{- range $hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /report.ReportAPI
        pathType: Prefix
        backend:
          service:
            name: {{ include "fogServices.fullname" $ }}-fog-report
            port:
              name: report-grpc
  {{- end }}
