# Copyright (c) 2018-2022 The MobileCoin Foundation
kind: ConfigMap
apiVersion: v1
metadata:
  name: fog-ingress-blacklist
  labels:
    {{- include "fogServicesConfig.labels" . | nindent 4 }}
data:
  BLACKLIST_ENABLED: {{ .Values.global.blacklist.enabled | squote }}
  BLACKLIST_PATTERN: {{ .Values.global.blacklist.pattern | squote }}
